<style>

    .form-group label{
        padding: 3px;
        margin:2px;
    }
</style>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">Team: <?php echo $this->user->getUsername(); ?></h4>
    </div>
    <div class="panel-body">

        <div class="">


            <?php
            $form = $this->form;
            $form->prepare();
            ?>

            <?php echo $this->form()->openTag($form) ?>

            <?php $element = $form->get('id') ?>
            <?php echo $this->formElement($element); ?>


            <?php $element = $form->get('teams') ?>

            <div style="" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                <label class="control-label" style="font-size: 12px; ">
                    <?php echo $element->getLabel() ?>
                </label>
                <div class="clearfix"></div>

                <?php echo $this->formElement($element); ?>



            </div>



            <?php $element = $form->get('submitbtn'); ?>
            <div style="" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">

                <?php echo $this->formElement($element); ?>

            </div>
            <?php echo $this->form()->closeTag(); ?>

        </div>

    </div>

</div>
