<?php 

$form->setAttribute('class', "form-horizontal");

?>

<?php echo $this->form()->openTag($form) ?>

<?php foreach ($form as $element): ?>
    <div class="form-group">
        <?php
        if ('submit' == $element->getAttribute('type')) {
            $element->setAttribute('class', 'btn btn-success');
        } else {
            $element->setAttribute('class', 'form-control')
                    ->setAttribute('placeholder', $element->getLabel());
        }
        ?>



        <?php $isButton = $element instanceof Zend\Form\Element\Button; ?>
        <?php $isCheckbox = $element instanceof Zend\Form\Element\Checkbox || $element->getAttribute('type') == 'checkbox'; ?>
        <?php if ($element->getLabel() != null && !$isButton): ?>
            <div class="col-lg-4 col-md-4 col-sm-5 col-xs-5 text-right">
                <label class="control-label" style="font-size: 12px; ">
                    <?php echo $element->getLabel() ?>
                </label>
            </div>
        <?php endif ?>
        <?php if ($isButton): ?>
            <div class="col-lg-8 col-md-8 col-sm-7 col-xs-7">
                <?php echo $this->formButton($element) ?>
            </div>
        <?php elseif ($element instanceof Zend\Form\Element\Select): ?>
            <div class="col-lg-8 col-md-8 col-sm-7 col-xs-7">
                <?php echo $this->formSelect($element) . $this->formElementErrors($element) ?>
            </div>
        <?php elseif ($element instanceof Zend\Form\Element\MultiCheckbox): ?>
            <div class="col-lg-8 col-md-8 col-sm-7 col-xs-7">
                <?php echo $this->formMultiCheckbox($element) . $this->formElementErrors($element) ?>
            </div>
        <?php elseif ($isCheckbox): ?>
            <div class="col-lg-8 col-md-8 col-sm-7 col-xs-7">
                <?php echo $this->formCheckbox($element) ?>
            </div>
        <?php else: ?>


            <div class="col-lg-8 col-md-8 col-sm-7 col-xs-7">
                <?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
            </div>
        <?php endif ?>
    </div>
<?php endforeach ?>

<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>">
<?php endif ?>
<?php echo $this->form()->closeTag() ?>