<?php
$form = $this->editUserForm;
$form->prepare();
$form->setAttribute('action', $this->url('cdiuser_admin/edit', array('userId' => $this->userId)));
$form->setAttribute('method', 'post');
?>

<div class="row" style="margin-top: 20px;">
    <div class="col-lg-2 center"></div>
    <div class="col-lg-8 center">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Edit user</h3>
            </div>
            <div class="panel-body">
                <?php include '_form.phtml'; ?>   
            </div>
            <div class="panel-footer">
                <a href="<?php echo $this->url('cdiuser_admin/list'); ?>">
                    <?php echo $this->translate('Cancelar') ?>
                </a>
                <a href="<?php echo $this->url('cdiuser_admin/remove', array('userId' => $this->userId)); ?>"
                   onclick="return confirm('<?php echo $this->translate('Really delete user?') ?>')">
                       <?php echo $this->translate('Eliminar') ?>
                </a>

            </div>

        </div>
    </div>



</div>

