 <div class="login-block">
            <div class="block block-transparent"> 
<h3><?php echo $this->translate('Recuperar Password'); ?></h3>
<?php
$form = $this->form;
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<?php $element = $form->get("email"); ?>

<div  class="form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
    <div class="col-lg-12">
        <label class="control-label"><?php echo ucfirst($this->translate($element->getLabel())); ?></label>
    </div>

    <div class="col-lg-12">
         <div class="input-group">
            <div class="input-group-addon">
                <span class="fa fa-at"></span>
            </div>
        <?php echo $this->formElement($element); ?>
         </div>
            <?php if ($element->getOption('description')): ?>
            <p class="help-block"><?php echo $element->getOption('description') ?></p>
        <?php endif; ?>

        <?php if ($this->formElementErrors($element)) : ?>
            <?php
            // Imprimo los errores
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<span class="help-block">')
                    ->setMessageSeparatorString('</span><span class="help-block">')
                    ->setMessageCloseString('</span>')
                    ->render($element);
            ?>

        <?php endif; ?>

    </div>
</div>

<?php $element = $form->get("submit"); ?>
<?php echo $this->formElement($element); ?>
<?php echo $this->form()->closeTag($form); ?>

   </div>
</div>
