<?php
$form = $this->createUserForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcadmin/zfcuseradmin/create'));
$form->setAttribute('method', 'post');
$form->setAttribute("role", "form");
?>

<div class="row" style="margin-top: 20px;">
      <div class="col-lg-2 center"></div>
    <div class="col-lg-8 center">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Create user</h3>
            </div>
            <div class="panel-body">
                <?php include '_form.phtml'; ?>   
            </div>

        </div>
    </div>



</div>