<div class="login-block">
    <div class="block block-transparent">

        <div class="head">
            
            <div class="user">
                <div class=" " style="opacity: 1;">                                                                                
                    <i class="fa fa-lock fa-2x" style="color: #444;"> Modificar Password</i>

                </div>                            
            </div>
     
        </div>

<?php echo $this->form()->closeTag(); ?>

        
<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Password modificada con exito.');?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-danger"><?php echo $this->translate('Error al cambiar su password. Por favor, intente nuevamente.'); ?></div>
<?php endif; ?>

<?php
    $form = $this->changePasswordForm;
 
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/changepassword'));
    $form->setAttribute('method', 'post');
 
    $emailElement = $form->get('identity');
    $emailElement->setValue($this->zfcUserIdentity()->getEmail());
 
    echo $this->form()->openTag($form);
?>
 
<?php foreach ($form as $element) : ?>
 
    <div  class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <?php
            if ('button' != $element->getAttribute('type')) { ?>
              
                <?php
                $element->setAttribute('class', 'btn btn-default btn-block btn-clean')
                        ->setAttribute('placeholder', $element->getLabel());
            } else {
                $element->setAttribute('class', 'btn btn-success');
            }
            if ($element instanceof Zend\Form\Element\Captcha) {
                echo $this->formCaptcha($element);
            } else {
                echo $this->formElement($element);
            }
            if ($this->formElementErrors($element)) : ?>
                <?php
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<p class="help-block">')
                    ->setMessageSeparatorString('</p><p class="help-block">')
                    ->setMessageCloseString('</p>')
                    ->render($element);
                ?>
            <?php endif; ?>
    </div>
 
<?php
endforeach;?>
<?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>

                </div>
    </div>
